apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: arc-admin
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: arc-admin-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: arc-admin
type: kubernetes.io/service-account-token